### ISSUE TITLE
[feature request] colored media flags and ratings

### ISSUE THREAD

**Issue by zeeyaullah** [pkscout/skin.arctic.zephyr.2.pkscout.mod#1]
Can we have the colored media flags and movie ratings (imdb, tmdb etc) like in Aura skin please. Is that possible? My request.

**Comment by pkscout** [comment]
Sorry, no.  This mod is feature complete.  At this point I'm only doing bug fixes or updates to keep it up to date with the original skin.  If you want that, please make the request of the original skin author.

**Comment by zeeyaullah** [comment]
Thanks
